### ISSUE TITLE
Logging written to read-only filesystem on mac

### ISSUE THREAD

**Issue by phargogh** [natcap/invest-workbench#142] opened 2021-04-20 20:20 UTC
When running the workbench for PR #133 , the application would work great, but then go blank.

To reproduce on my mac (Mac OS X Big Sur):

* Clone the workbench, checkout revision `c04ac943dcb4a14560925a7288c1cd63ef5f2df1`
* Build the application (`npm run build && npm run dist`)
* Mount the disk image and copy the application to `/Applications`
* Open the application (launches fine for me)
* Observe that the UI looks great
* 2-4 seconds in to the launch, the page goes blank.
* Open the developer console, observe errors.
* To repeat, refresh the page.

Screenshot of the errors:
<img width="557" alt="Screen Shot 2021-04-20 at 3 13 42 PM" src="https://user-images.githubusercontent.com/4583897/115458743-bc17e080-a1eb-11eb-8566-d66c0dcfe25b.png">

Once the errors appear, I then see an error about react-devtools not being connected.  I'm guessing because node has shut down by that point?
<img width="510" alt="Screen Shot 2021-04-20 at 3 21 59 PM" src="https://user-images.githubusercontent.com/4583897/115459225-6b54b780-a1ec-11eb-8655-62fd5908f8b0.png">

And also, just before the errors appear, the model name list appears to have a pile of react attributes that aren't model names themselves:
<img width="329" alt="Screen Shot 2021-04-20 at 3 22 11 PM" src="https://user-images.githubusercontent.com/4583897/115459324-8aebe000-a1ec-11eb-80a3-30c20ca3d477.png">

**Comment by davemfish** [comment] 2021-04-20 20:29
@phargogh did you also do a `npm run fetch-invest` as part of the build process? Perhaps we should combine that into `npm run build` to make it harder to forget. It also looks like we should do better error-handling if it is an incompatible invest exe at the root of this issue.

**Comment by davemfish** [comment] 2021-04-20 20:34
Oh wait I missed the part where you said the UI looks great at first, hmmm that's harder to explain.

**Comment by phargogh** [comment] 2021-05-14 16:09
We've got a refactor in progress, so putting on hold until that's complete.

**Comment by davemfish** [comment] 2021-06-23 16:07
We've done the refactor and also switched to `electron-log` for logging (#147 ), so we could check back to see if this is still reproducible.

**Comment by davemfish** [comment] 2021-10-04 14:07
@phargogh do you think it's safe to close this one? I haven't specifically tried to reproduce it, but I have run the WB on MacOS recently and it hasn't come up.

**Comment by phargogh** [comment] 2021-10-04 15:42
Yeah, I haven't seen this issue recently.  Let's close!

**Closed** 2021-10-04 15:42 UTC
Labels: bug, on hold
